export const WORKOUT_PLAN_ENROLL_REQUEST = "WORKOUT_PLAN_ENROLL_REQUEST";
export const WORKOUT_PLAN_ENROLL_SUCCESS = "WORKOUT_PLAN_ENROLL_SUCCESS";
export const WORKOUT_PLAN_ENROLL_FAILED = "WORKOUT_PLAN_ENROLL_FAILED";

export const GET_WORKOUT_PLAN_LIST_REQUEST = "GET_WORKOUT_PLAN_LIST_REQUEST";
export const GET_WORKOUT_PLAN_LIST_SUCCESS = "GET_WORKOUT_PLAN_LIST_SUCCESS";
export const GET_WORKOUT_PLAN_LIST_FAILED = "GET_WORKOUT_PLAN_LIST_FAILED";

export const GET_WORKOUT_PLAN_DETAILS_REQUEST =
  "GET_WORKOUT_PLAN_DETAILS_REQUEST";
export const GET_WORKOUT_PLAN_DETAILS_SUCCESS =
  "GET_WORKOUT_PLAN_DETAILS_SUCCESS";
export const GET_WORKOUT_PLAN_DETAILS_FAILED =
  "GET_WORKOUT_PLAN_DETAILS_FAILED";

export const SUBMIT_COMPLETED_WORKOUT_REQUEST =
  "SUBMIT_COMPLETED_WORKOUT_REQUEST";
export const SUBMIT_COMPLETED_WORKOUT_SUCCESS =
  "SUBMIT_COMPLETED_WORKOUT_SUCCESS";
export const SUBMIT_COMPLETED_WORKOUT_FAILED =
  "SUBMIT_COMPLETED_WORKOUT_FAILED";

export const GET_USER_ENROLLED_WORKOUT_PLAN_REQUEST =
  "GET_USER_ENROLLED_WORKOUT_PLAN_REQUEST";
export const GET_USER_ENROLLED_WORKOUT_PLAN_SUCCESS =
  "GET_USER_ENROLLED_WORKOUT_PLAN_SUCCESS";
export const GET_USER_ENROLLED_WORKOUT_PLAN_FAILED =
  "GET_USER_ENROLLED_WORKOUT_PLAN_FAILED";

export const ADD_WEIGHT_REQUEST = "ADD_WEIGHT_REQUEST";
export const ADD_WEIGHT_SUCCESS = "ADD_WEIGHT_SUCCESS";
export const ADD_WEIGHT_FAILED = "ADD_WEIGHT_FAILED";

export const GET_WEIGHT_LIST_REQUEST = "GET_WEIGHT_LIST_REQUEST";
export const GET_WEIGHT_LIST_SUCCESS = "GET_WEIGHT_LIST_SUCCESS";
export const GET_WEIGHT_LIST_FAILED = "GET_WEIGHT_LIST_FAILED";

export const ADD_CHEAT_MEAL_REQUEST = "ADD_CHEAT_MEAL_REQUEST";
export const ADD_CHEAT_MEAL_SUCCESS = "ADD_CHEAT_MEAL_SUCCESS";
export const ADD_CHEAT_MEAL_FAILED = "ADD_CHEAT_MEAL_FAILED";

export const GET_CHEAT_MEAL_LIST_REQUEST = "GET_CHEAT_MEAL_LIST_REQUEST";
export const GET_CHEAT_MEAL_LIST_SUCCESS = "GET_CHEAT_MEAL_LIST_SUCCESS";
export const GET_CHEAT_MEAL_LIST_FAILED = "GET_CHEAT_MEAL_LIST_FAILED";

export const GET_REPORT_DATA_REQUEST = "GET_REPORT_DATA_REQUEST";
export const GET_REPORT_DATA_SUCCESS = "GET_REPORT_DATA_SUCCESS";
export const GET_REPORT_DATA_FAILED = "GET_REPORT_DATA_FAILED";

export const GET_USER_LAST_WEIGHT_REQUEST = "GET_USER_LAST_WEIGHT_REQUEST";
export const GET_USER_LAST_WEIGHT_SUCCESS = "GET_USER_LAST_WEIGHT_SUCCESS";
export const GET_USER_LAST_WEIGHT_FAILED = "GET_USER_LAST_WEIGHT_FAILED";

export const GET_USER_PREDICTION_DATA_REQUEST =
  "GET_USER_PREDICTION_DATA_REQUEST";
export const GET_USER_PREDICTION_DATA_SUCCESS =
  "GET_USER_PREDICTION_DATA_SUCCESS";
export const GET_USER_PREDICTION_DATA_FAILED =
  "GET_USER_PREDICTION_DATA_FAILED";
